[global]
developmentMode = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = false
port = 8501
maxUploadSize = 200
runOnSave = false
fileWatcherType = "none"
allowRunOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[logger]
level = "info"

[client]
showErrorDetails = true

[runner]
# 允许公开访问
magicEnabled = true
installTracer = false
fixMatplotlib = true
